/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Accounts {
  access_token: string | null;
  created_at: string;
  expires_at: string | null;
  id: string;
  provider: string;
  provider_account_id: string;
  refresh_token: string | null;
  updated_at: string | null;
  user_id: string;
}

export interface RtmTimelines {
  created_at: string;
  expires_at: string;
  id: string;
  timeline: string;
  user_id: string;
}

export interface RtmTokens {
  auth_token: string;
  fullname: string | null;
  perms: string;
  status: string;
  updated_at: string;
  user_id: string;
  username: string | null;
}

export interface Sessions {
  created_at: string;
  expires_at: string;
  id: string;
  ip_address: string | null;
  token: string;
  updated_at: string | null;
  user_agent: string | null;
  user_id: string;
}

export interface Users {
  created_at: string;
  email: string;
  email_verified: Generated<number>;
  id: string;
  image: string | null;
  name: string | null;
  updated_at: string;
}

export interface WebhookSubs {
  created_at: string;
  expires_at: string | null;
  filter: string | null;
  id: string;
  lease_seconds: number | null;
  status: string;
  subscription_id: string;
  topics: string;
  updated_at: string;
  url: string;
  user_id: string;
}

export interface DB {
  accounts: Accounts;
  rtm_timelines: RtmTimelines;
  rtm_tokens: RtmTokens;
  sessions: Sessions;
  users: Users;
  webhook_subs: WebhookSubs;
}
