/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  access_token: string | null;
  accessTokenExpiresAt: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  provider: string;
  provider_account_id: string;
  refresh_token: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Apikey {
  config_id: Generated<string>;
  createdAt: Timestamp;
  enabled: boolean | null;
  expiresAt: Timestamp | null;
  id: string;
  key: string;
  lastRefillAt: Timestamp | null;
  lastRequest: Timestamp | null;
  metadata: string | null;
  name: string | null;
  permissions: string | null;
  prefix: string | null;
  rateLimitEnabled: boolean | null;
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  refillAmount: number | null;
  refillInterval: number | null;
  remaining: number | null;
  requestCount: number | null;
  start: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Jwks {
  createdAt: Timestamp;
  expiresAt: Timestamp | null;
  id: string;
  privateKey: string;
  publicKey: string;
}

export interface OauthAccessToken {
  clientId: string;
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  referenceId: string | null;
  refreshId: string | null;
  scopes: Json;
  sessionId: string | null;
  token: string;
  userId: string | null;
}

export interface OauthClient {
  clientId: string;
  clientSecret: string | null;
  contacts: Json | null;
  createdAt: Timestamp | null;
  disabled: Generated<boolean | null>;
  enableEndSession: boolean | null;
  grantTypes: Json | null;
  icon: string | null;
  id: string;
  metadata: Json | null;
  name: string | null;
  policy: string | null;
  postLogoutRedirectUris: Json | null;
  public: boolean | null;
  redirectUris: Json;
  referenceId: string | null;
  requirePKCE: boolean | null;
  responseTypes: Json | null;
  scopes: Json | null;
  skipConsent: boolean | null;
  softwareId: string | null;
  softwareStatement: string | null;
  softwareVersion: string | null;
  subjectType: string | null;
  tokenEndpointAuthMethod: string | null;
  tos: string | null;
  type: string | null;
  updatedAt: Timestamp | null;
  uri: string | null;
  userId: string | null;
}

export interface OauthConsent {
  clientId: string;
  createdAt: Timestamp;
  id: string;
  referenceId: string | null;
  scopes: Json;
  updatedAt: Timestamp;
  userId: string;
}

export interface OauthRefreshToken {
  authTime: Timestamp | null;
  clientId: string;
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  referenceId: string | null;
  revoked: Timestamp | null;
  scopes: Json;
  sessionId: string | null;
  token: string;
  userId: string;
}

export interface RtmTimelines {
  created_at: Timestamp;
  expires_at: Timestamp;
  id: string;
  timeline: string;
  user_id: string;
}

export interface RtmTokens {
  auth_token: string;
  fullname: string | null;
  perms: string;
  status: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  username: string | null;
}

export interface Session {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  ip_address: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface User {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: boolean;
  id: string;
  image: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface WebhookSubs {
  created_at: Timestamp;
  expires_at: Timestamp | null;
  filter: string | null;
  id: string;
  lease_seconds: number | null;
  status: string;
  subscription_id: string;
  topics: string;
  updated_at: Generated<Timestamp>;
  url: string;
  user_id: string;
}

export interface DB {
  account: Account;
  apikey: Apikey;
  jwks: Jwks;
  oauthAccessToken: OauthAccessToken;
  oauthClient: OauthClient;
  oauthConsent: OauthConsent;
  oauthRefreshToken: OauthRefreshToken;
  rtm_timelines: RtmTimelines;
  rtm_tokens: RtmTokens;
  session: Session;
  user: User;
  verification: Verification;
  webhook_subs: WebhookSubs;
}
